package g5.dashboard.backend;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import java.util.*;

@RestController // This means that this class is a Controller
@CrossOrigin(origins = "*")
public class MainController {
  // This means to get the bean called recordRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private RecordRepository recordRepository;
  
  @Autowired
  private PerdaRepository perdaRepository;

  /* ***************************** */
  /* CALCULOS DE EVENTO DE MAQUINA */
  /* ***************************** */

  @GetMapping({"/oee/{cod}", "/oee"})
  public ApiOeeResponse equipamentoOee(@PathVariable Optional<String> cod,
                                       @RequestParam Optional<Integer> ano,
                                       @RequestParam Optional<Integer> mes) {
    String codArg = cod.orElse(null);  /* Nulo se não foi recebido */
    Integer mesArg = mes.orElse(null); /* Nulo se não foi recebido */
    Integer anoArg = ano.orElse(null); /* Nulo se não foi recebido */

    System.out.println(codArg);
    System.out.println(mesArg);
    System.out.println(anoArg);

    String tipoPeriodo;
    /* Este trecho resgasta o período ativo.
    Que pode ser um conjunto de: Anos, meses ou dias. 
    O Argumento de máquina é opcional */
    Iterable<Integer> periodoAtivo;
    if (mesArg != null) {
      /* Resgata dias ativos de um ano e um mes específico */
      tipoPeriodo = "diario";
      periodoAtivo = recordRepository.getDiasAtivos(
        codArg,
        anoArg,
        mesArg
      );
    } else if (anoArg != null) {
      /* Resgata meses ativos de um ano específico */
      tipoPeriodo = "mensal";
      periodoAtivo = recordRepository.getMesesAtivos(
        codArg,
        anoArg
      );
    } else {
      /* Resgata anos ativos desde o começo */
      tipoPeriodo = "anual";
      periodoAtivo = recordRepository.getAnosAtivos(
        codArg
      );
    }

    /* Para cada período (ano, mes ou dia), 
    associar o OEE do mesmo */
    Map<Integer, Double> oees = new HashMap<Integer, Double>();
    if (tipoPeriodo.equals("diario")) {
      for (Integer p : periodoAtivo) {
        oees.put(
          p,
          recordRepository.getDisponibilidade(codArg, anoArg, mesArg, p) *
          recordRepository.getQualidade(codArg, anoArg, mesArg, p) *
          recordRepository.getPerformance(codArg, anoArg, mesArg, p) * 100
        );
      }
    } else if (tipoPeriodo.equals("mensal")) {
      for (Integer p : periodoAtivo) {
        oees.put(
          p,
          recordRepository.getDisponibilidade(codArg, anoArg, p, null) *
          recordRepository.getQualidade(codArg, anoArg, p, null) *
          recordRepository.getPerformance(codArg, anoArg, p, null) * 100
        );
      }
    } else {
      for (Integer p : periodoAtivo) {
        oees.put(
          p,
          recordRepository.getDisponibilidade(codArg, p, null, null) *
          recordRepository.getQualidade(codArg, p, null, null) *
          recordRepository.getPerformance(codArg, p, null, null) * 100
        );
      }
    }

    System.out.println(periodoAtivo);      

    ApiOeeResponse response = new ApiOeeResponse();
    response.setNomeEquipamento(codArg);
    response.setTipoPeriodo(tipoPeriodo);
    response.setOees(oees);
    return response;
  }  

  @GetMapping({"/performance/{cod}", "/performance"})
  public Double calculoPerformance(@PathVariable Optional<String> cod,
                                   @RequestParam Optional<Integer> ano, 
                                   @RequestParam Optional<Integer> mes,
                                   @RequestParam Optional<Integer> dia) {
    Double calculo = recordRepository.getPerformance(
      cod.orElse(null),
      ano.orElse(null),
      mes.orElse(null),
      dia.orElse(null)
    );
    return calculo;
  }

  @GetMapping({"/qualidade/{cod}", "/qualidade"})
  public Double calculoQualidade(@PathVariable Optional<String> cod,
                                 @RequestParam Optional<Integer> ano, 
                                 @RequestParam Optional<Integer> mes,
                                 @RequestParam Optional<Integer> dia) {
    Double calculo = recordRepository.getQualidade(
      cod.orElse(null),
      ano.orElse(null),
      mes.orElse(null),
      dia.orElse(null)
    );
    return calculo;
  }

  @GetMapping({"/disponibilidade/{cod}", "/disponibilidade"})
  public Double calculoDisponibilidade(@PathVariable Optional<String> cod,
                                  @RequestParam Optional<Integer> ano, 
                                  @RequestParam Optional<Integer> mes,
                                  @RequestParam Optional<Integer> dia) {
    Double calculo = recordRepository.getDisponibilidade(
      cod.orElse(null),
      ano.orElse(null),
      mes.orElse(null),
      dia.orElse(null)
    );
    return calculo;
  }

  /* ************************** */
  /* CALCULOS DE PERDAS DA ÁREA */
  /* ************************** */

  @GetMapping({"/parada/{tipo}", "/parada"})
  public ApiParadaResponse calculoPerda(
                             @PathVariable Optional<String> tipo,
                             @RequestParam Optional<Integer> ano, 
                             @RequestParam Optional<Integer> mes) {
    String tipoArg = tipo.orElse(null);  /* Nulo se não foi recebido */
    Integer mesArg = mes.orElse(null); /* Nulo se não foi recebido */
    Integer anoArg = ano.orElse(null); /* Nulo se não foi recebido */
    String tipoPeriodo;

    // Caractere de escape
    if (tipoArg != null) {
      tipoArg = tipoArg.replace("_", "/");
      tipoArg = tipoArg.replace("%20", " ");
    }

    System.out.println(tipoArg);
    System.out.println(mesArg);
    System.out.println(anoArg);

    /* Este trecho resgasta o período ativo.
    Que pode ser um conjunto de: Anos, meses ou dias. 
    O Argumento de máquina é opcional */
    Iterable<Integer> periodoAtivo;
    if (mesArg != null) {
      /* Resgata dias ativos de um ano e um mes específico */
      tipoPeriodo = "diario";
      periodoAtivo = perdaRepository.getDiasAtivos(
        tipoArg,
        anoArg,
        mesArg
      );
    } else if (anoArg != null) {
      /* Resgata meses ativos de um ano específico */
      tipoPeriodo = "mensal";
      periodoAtivo = perdaRepository.getMesesAtivos(
        tipoArg,
        anoArg
      );
    } else {
      /* Resgata anos ativos desde o começo */
      tipoPeriodo = "anual";
      periodoAtivo = perdaRepository.getAnosAtivos(
        tipoArg
      );
    }

    /* Para cada período (ano, mes ou dia), 
    associar o tempo de parada do mesmo */
    Map<Integer, Double> paradas = new HashMap<Integer, Double>();
    if (tipoPeriodo.equals("diario")) {
      for (Integer p : periodoAtivo) {
        paradas.put(
          p,
          perdaRepository.getParada(
            tipoArg,
            anoArg,
            mesArg,
            p
          )
        );
      }
    } else if (tipoPeriodo.equals("mensal")) {
      for (Integer p : periodoAtivo) {
        paradas.put(
          p,
          perdaRepository.getParada(
            tipoArg,
            anoArg,
            p,
            null
          )
        );
      }
    } else {
      for (Integer p : periodoAtivo) {
        paradas.put(
          p,
          perdaRepository.getParada(
            tipoArg,
            p,
            null,
            null
          )
        );
      }
    }

    System.out.println(periodoAtivo);      

    ApiParadaResponse response = new ApiParadaResponse();
    response.setTipoParada(tipoArg);
    response.setTipoPeriodo(tipoPeriodo);
    response.setParadas(paradas);
    return response;
  }



  @GetMapping({"/perdas/{tipo}", "/perdas"})
  public Map<String, Double> calculoPerda(@PathVariable Optional<String> tipo) {
    String tipoArg = tipo.orElse(null);

    // Caractere de escape
    if (tipoArg != null) {
      tipoArg = tipoArg.replace("_", "/");
      tipoArg = tipoArg.replace("%20", " ");
    }

    /* Resgata todas as categorias 
    que pode ser um destes dois: 
    1 - Tipo de falha
    2 - Disfuncao de processo (subset de um tipo) */
    Iterable<String> categorias;
    if (tipoArg != null) {
      categorias = perdaRepository.getDistinctDisfuncaoProcesso(tipoArg);
    } else {
      categorias = perdaRepository.getDistinctTipoFalha();
    }
    
    /* Calcula a porcentagem de cada um, comparado ao todo */
    Map<String, Double> porcentagens = new HashMap<String, Double>();
    if (tipoArg != null) {
      /* Pega cada disfunção de 
      processo e sua porcentagem */
      for (String c : categorias) {
        porcentagens.put(
          c,
          perdaRepository.getPorcentagemDisfuncaoProcesso(tipoArg, c) * 100
        );
      }
    } else {
      /* Pega cada tipo de 
      falha e sua porcentagem */
      for (String c : categorias) {
        porcentagens.put(
          c,
          perdaRepository.getPorcentagemTipoFalha(c) * 100
        );
      }
    }

    return porcentagens;
  }
}