package g5.dashboard.backend;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import java.util.*;

@RestController // This means that this class is a Controller
@CrossOrigin(origins = "*")
public class MainController {
  // This means to get the bean called recordRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private RecordRepository recordRepository;
  
  @Autowired
  private PerdaRepository perdaRepository;

  @GetMapping("/equipment/{code}")
  public ApiEquipmentResponse equipmentAnnualOees(@PathVariable String code) {
    Iterable<Integer> activeYears = recordRepository.findYearsByEquipment(code);
    
    Map<Integer, Double> annualOee = new HashMap<Integer, Double>();
    for (Integer year : activeYears) {
      annualOee.put(year, recordRepository.getAnnualOee(code, year));
    }
    
    ApiEquipmentResponse response = new ApiEquipmentResponse();
    response.setEquipmentName(code);
    response.setOees(annualOee);
    return response;
  }  

  @GetMapping("/perda/{year}")
  public Double yearlyPerda(@PathVariable Integer year) {
    Double somaParadas = perdaRepository.getSomadasParadas(year);
    return somaParadas;
  }  



}