package g5.dashboard.backend;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import java.util.*;

@RestController // This means that this class is a Controller
@CrossOrigin(origins = "*")
public class MainController {
  // This means to get the bean called recordRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private RecordRepository recordRepository;
  
  @Autowired
  private PerdaRepository perdaRepository;

  @GetMapping("/equipment/{code}")
  public ApiEquipmentResponse equipmentAnnualOees(@PathVariable String code) {
    Iterable<Integer> activeYears = recordRepository.findYearsByEquipment(code);
    
    Map<Integer, Double> annualOee = new HashMap<Integer, Double>();
    for (Integer year : activeYears) {
      annualOee.put(year, recordRepository.getAnnualOee(code, year));
    }
    
    ApiEquipmentResponse response = new ApiEquipmentResponse();
    response.setEquipmentName(code);
    response.setOees(annualOee);
    return response;
  }  

  @GetMapping("/record/{code}/{day}/{month}/{year}")
  public Double recordGeralDiaria(@PathVariable String code,
  @PathVariable Integer day, @PathVariable Integer month, @PathVariable Integer year) {
   
    Double testeRecord = 0.0;

    /* Se não tem máquina */
    if (code.equals("0")) {
      if (day != 0)
      testeRecord = recordRepository.getPerformanceGeralDiario(day,month,year);
      else if (month != 0)
      testeRecord = recordRepository.getPerformanceGeralMensal(month,year);
      else if (year != 0)
      testeRecord = recordRepository.getPerformanceGeralAnual(year);
      else
      testeRecord = recordRepository.getPerformanceGeral();
   }
  /* Se tem máquina */
    else {
      if (day != 0)
      testeRecord = recordRepository.getPerformanceDiario(code,day,month,year);
      else if (month != 0)
      testeRecord = recordRepository.getPerformanceMensal(code,month,year);
      else if (year != 0)
      testeRecord = recordRepository.getPerformanceAnual(code,year);
    } 
    return testeRecord;
}

  @GetMapping("/perda/{tipo}/{ano}/{mes}/{dia}")
  public Double perdaGeralDiaria(@PathVariable String tipo,
  @PathVariable Integer ano, @PathVariable Integer mes, @PathVariable Integer dia) {
    /* Substitui _ com barras */
    tipo.replace('_', '/');
     
    Double somaParadas;
    /* Se não tem tipo */
    if (tipo.equals("0")) {
      if (dia != 0)
        somaParadas = perdaRepository.getParadaGeralDiaria(ano,mes,dia);
      else if (mes != 0)
        somaParadas = perdaRepository.getParadaGeralMensal(ano,mes);
      else if (ano != 0)
        somaParadas = perdaRepository.getParadaGeralAnual(ano);
      else
        somaParadas = perdaRepository.getParadaGeral();
    }
    /* Se tem tipo */
    else {
      if (dia != 0)
        somaParadas = perdaRepository.getParadaDiaria(ano,mes,dia,tipo);
      else if (mes != 0)
        somaParadas = perdaRepository.getParadaMensal(ano,mes,tipo);
      else if (ano != 0)
        somaParadas = perdaRepository.getParadaAnual(ano,tipo);
      else
        somaParadas = perdaRepository.getParada(tipo);
    }

    return somaParadas;
  }  
}